// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTr7TfmEWhHMdhj9rBWXhYL3DVwQNNmxM',
    appId: '1:849655606704:web:da3e3543d273e80a8c7a75',
    messagingSenderId: '849655606704',
    projectId: 'berryapp-e4d54',
    authDomain: 'berryapp-e4d54.firebaseapp.com',
    storageBucket: 'berryapp-e4d54.firebasestorage.app',
    measurementId: 'G-SKD2CJ6B6N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWB-7KBmvRgwDxAOKlfNmCJaxn-nzU6cA',
    appId: '1:849655606704:android:eeb4ffd1376f9c588c7a75',
    messagingSenderId: '849655606704',
    projectId: 'berryapp-e4d54',
    storageBucket: 'berryapp-e4d54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi1NmpZNkUlOdZXjB-A_SznpyUrK8pd7o',
    appId: '1:849655606704:ios:8320f001732e7eb28c7a75',
    messagingSenderId: '849655606704',
    projectId: 'berryapp-e4d54',
    storageBucket: 'berryapp-e4d54.firebasestorage.app',
    iosClientId: '849655606704-tpavdf475n3u9qmic9kq68h8lc98guca.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi1NmpZNkUlOdZXjB-A_SznpyUrK8pd7o',
    appId: '1:849655606704:ios:8320f001732e7eb28c7a75',
    messagingSenderId: '849655606704',
    projectId: 'berryapp-e4d54',
    storageBucket: 'berryapp-e4d54.firebasestorage.app',
    iosClientId: '849655606704-tpavdf475n3u9qmic9kq68h8lc98guca.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTr7TfmEWhHMdhj9rBWXhYL3DVwQNNmxM',
    appId: '1:849655606704:web:f826a724fc50ec278c7a75',
    messagingSenderId: '849655606704',
    projectId: 'berryapp-e4d54',
    authDomain: 'berryapp-e4d54.firebaseapp.com',
    storageBucket: 'berryapp-e4d54.firebasestorage.app',
    measurementId: 'G-J3Z65ZBKR4',
  );
}
