name: Build-Android-APK

permissions:
  contents: write
  packages: write

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) ソース取得
      - uses: actions/checkout@v4

      # 2) Flutter セットアップ
      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      # 3) 依存解決
      - run: flutter pub get

      # 4) ビルド変数 (GEMINI_KEY など)
      - run: echo "GEMINI_KEY=${{ secrets.GEMINI_KEY }}" >> $GITHUB_ENV

      # 5) リリース APK ビルド
      - run: flutter build apk --release --dart-define=GEMINI_KEY=${{ env.GEMINI_KEY }}

      # ── これ 1 つで 「タグ作成＋APK添付」 を同時実行 ──
      - name: Release APK
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.run_id }}-${{ github.run_number }}
          name: Build ${{ github.run_id }}
          draft: false
          prerelease: false
          files: build/app/outputs/flutter-apk/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

