name: Build-Android-APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      - run: echo "GEMINI_KEY=${{ secrets.GEMINI_KEY }}" >> $GITHUB_ENV
      - run: flutter build apk --release --dart-define=GEMINI_KEY=${{ env.GEMINI_KEY }}
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: BabyBerry-APK
          path: build/app/outputs/flutter-apk/app-release.apk
